version: '2'

services:
  btc:
    container_name: btc-service
    build: ./btc/
    ports:
      - "17416:7416"
      - "17316:7316"
      - "17317:7317"
      - "17424:7424"
      - "14444:4444"
      - "18080:8080"
      - "18081:8081"
      - "18091:8091"
    depends_on:
      - mysql
      - kafka
      - redis_sentinel
      - redis_slave
      - redis_master
    links:
      - mysql:db
      - kafka:mq
      - redis_sentinel
      - redis_slave
      - redis_master

  redis_master:
    container_name: btc-redis-master
    image: redis:4.0.2-alpine
    ports:
      - "16379:6379"

  redis_slave:
    container_name: btc-redis-slave
    image: redis:4.0.2-alpine
    ports:
      - "16380:6379"

  redis_sentinel:
    container_name: btc-redis-sentinel
    build: redis
    image: redis-sentinel
    environment:
      - MASTER_NAME=mymaster
      - QUORUM=1
      - MASTER=redis_master
      - SLAVES=redis_slave
    depends_on:
      - redis_master
    ports:
      - "26379:26379"

  mysql:
    container_name: btc-mysql
    build: ./db/
    ports:
      - "13306:3306"

  zookeeper:
    container_name: btc-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "12181:2181"

  kafka:
    container_name: btc-kafka
    image: wurstmeister/kafka
    links:
      - zookeeper
    ports:
      - "19092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: mq
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
